name: flutter_qrcode_scanner
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^5.0.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.2.1
  get: 4.6.1
  glassmorphism_ui: ^0.2.0
  google_fonts: ^2.1.0
  image_picker: ^0.8.5+3
  mobile_scanner: ^1.0.0
  qr_flutter: ^4.0.0
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/qr_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/qr_icon.png
  android_12:
